//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Dispositivo.Resource {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class DispositivoReconhecimentoTerrenoResource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal DispositivoReconhecimentoTerrenoResource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Dispositivo.Resource.DispositivoReconhecimentoTerrenoResource", typeof(DispositivoReconhecimentoTerrenoResource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Favor inserir dados válidos. Modelo de eexmplo para uma matriz 3 por 5: &quot;3 5&quot;.
        /// </summary>
        public static string ERRO_INPUT_INCORRETO {
            get {
                return ResourceManager.GetString("ERRO_INPUT_INCORRETO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Coluna: .
        /// </summary>
        public static string LABEL_COLUNA {
            get {
                return ResourceManager.GetString("LABEL_COLUNA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Linha: .
        /// </summary>
        public static string LABEL_LINHA {
            get {
                return ResourceManager.GetString("LABEL_LINHA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mapa água:.
        /// </summary>
        public static string MAPA_AGUA {
            get {
                return ResourceManager.GetString("MAPA_AGUA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mapa mina terrestre:.
        /// </summary>
        public static string MAPA_MINA {
            get {
                return ResourceManager.GetString("MAPA_MINA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mapa obstáculo:.
        /// </summary>
        public static string MAPA_OBSTACULO {
            get {
                return ResourceManager.GetString("MAPA_OBSTACULO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 2 - Área de atenção.
        /// </summary>
        public static string MENSAGEM_AREA_ATENCAO {
            get {
                return ResourceManager.GetString("MENSAGEM_AREA_ATENCAO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 4 - Área não recomendada.
        /// </summary>
        public static string MENSAGEM_AREA_NAO_RECOMENDADA {
            get {
                return ResourceManager.GetString("MENSAGEM_AREA_NAO_RECOMENDADA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 3 - Área perigosa.
        /// </summary>
        public static string MENSAGEM_AREA_PERIGOSA {
            get {
                return ResourceManager.GetString("MENSAGEM_AREA_PERIGOSA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1 - Área segura.
        /// </summary>
        public static string MENSAGEM_AREA_SEGURA {
            get {
                return ResourceManager.GetString("MENSAGEM_AREA_SEGURA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Possui uma ilhota estratégicamente útil na posição:
        ///linha: {0}, coluna: {1}. 0% chance de bombas, água em todos os lados, não possui obstáculo..
        /// </summary>
        public static string MENSAGEM_ILHOTA_ESTRATEGICA {
            get {
                return ResourceManager.GetString("MENSAGEM_ILHOTA_ESTRATEGICA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Insira o número de linhas e colunas presentes no mapa, separados por um espaço..
        /// </summary>
        public static string MENSAGEM_INSIRA_DADOS {
            get {
                return ResourceManager.GetString("MENSAGEM_INSIRA_DADOS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Não possui uma ilhota estratégicamente útil..
        /// </summary>
        public static string MENSAGEM_NAO_POSSUI_ILHOTA_ESTRATEGICA {
            get {
                return ResourceManager.GetString("MENSAGEM_NAO_POSSUI_ILHOTA_ESTRATEGICA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Porcentagem ocupada por água/obstáculo: {0} %..
        /// </summary>
        public static string MENSAGEM_OCUPADA_AGUA_OBSTACULO {
            get {
                return ResourceManager.GetString("MENSAGEM_OCUPADA_AGUA_OBSTACULO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Perigo no terreno: {0} % - Nível {1}..
        /// </summary>
        public static string MENSAGEM_PERIGO_TERRENO {
            get {
                return ResourceManager.GetString("MENSAGEM_PERIGO_TERRENO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Profundidade média: {0} metro(s)..
        /// </summary>
        public static string MENSAGEM_PROFUNDIDADE_MEDIA {
            get {
                return ResourceManager.GetString("MENSAGEM_PROFUNDIDADE_MEDIA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Travessia somente na coluna: {0}. Perigo: {1}%..
        /// </summary>
        public static string MENSAGEM_TRAVESSIA_COLUNA {
            get {
                return ResourceManager.GetString("MENSAGEM_TRAVESSIA_COLUNA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Não existem linhas e colunas possíves de atravessar..
        /// </summary>
        public static string MENSAGEM_TRAVESSIA_INEXISTENTE {
            get {
                return ResourceManager.GetString("MENSAGEM_TRAVESSIA_INEXISTENTE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Travessia somente na linha: {0}. Perigo: {1}%..
        /// </summary>
        public static string MENSAGEM_TRAVESSIA_LINHA {
            get {
                return ResourceManager.GetString("MENSAGEM_TRAVESSIA_LINHA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Travessia nas seguintes linha(s)/colunas(s):.
        /// </summary>
        public static string MENSAGEM_TRAVESSIA_LINHAS_COLUNAS {
            get {
                return ResourceManager.GetString("MENSAGEM_TRAVESSIA_LINHAS_COLUNAS", resourceCulture);
            }
        }
    }
}
